### ISSUE TITLE
curious about the scenes will automatically updated by auth state ?

### ISSUE THREAD

**Issue by pannz** [iZaL/my-appointment#2]
I'm quite curious about when the  state changes,  the scene will automatically update ?

if the  auth state updated, then the connected App will receive the `isAuthenticated` by its selector ,  but the render method didn't handle the `isAuthenticated`, so how the scene reset to the authed "main" scene

this just read the ./App.js  ./Root.js  ./scenes.js as a great example for writing my app, and I can't run up the cloned app (maybe I need do some work with xcode, I just cloned and install and then react-native run-ios but build failed), so that's my curiosity 

thanks

**Comment by iZaL** [comment]
Please pull the changes. The App should run fine now. And don't forget to run 'react-native link' should you have problem with native dependencies.

**Comment by pannz** [comment]
👍 got it
